# SPDX-FileCopyrightText: 2026 QuantGlass contributors
# SPDX-License-Identifier: AGPL-3.0-or-later

from __future__ import annotations

from quantglass_sdk import (
    ExtensionManifest,
    ExtensionSetting,
    ExtensionSurfaceDefinition,
    IndicatorDefinition,
    StrategyDefinition,
)


def _community_momentum_candidates(context: dict[str, object]) -> list[dict[str, object]]:
    close = float(context.get("close") or 0)
    ema21 = float(context.get("ema21") or 0)
    sma50 = float(context.get("sma50") or 0)
    rsi14 = float(context.get("rsi14") or 0)
    atr14 = float(context.get("atr14") or 0)
    volume_ratio = float(context.get("volume_ratio") or 0)
    trend_alignment = float(context.get("trend_alignment") or 0)
    volume_confirmation = float(context.get("volume_confirmation") or 0)
    volatility_regime = str(context.get("volatility_regime") or "normal")
    regime = str(context.get("regime") or "transitional")

    if close <= 0 or atr14 <= 0:
        return []
    if not (close > ema21 > sma50 and 50 <= rsi14 <= 76 and volume_ratio >= 0.85):
        return []

    risk = max(atr14 * 1.35, close * 0.006)
    confluence = min(0.92, 0.48 + trend_alignment * 0.18 + volume_confirmation * 0.16)
    return [
        {
            "signal": "WATCH",
            "setup_type": "community_momentum_pullback",
            "direction": "long",
            "status": "active",
            "regime": regime,
            "risk_level": "medium" if volatility_regime != "expanded" else "high",
            "reference_price": close,
            "entry_zone": [close * 0.995, close * 1.005],
            "stop_loss": close - risk,
            "take_profit": [close + risk, close + risk * 1.8, close + risk * 2.8],
            "trend_alignment": trend_alignment,
            "volume_confirmation": volume_confirmation,
            "volatility_regime": volatility_regime,
            "confluence_score": confluence,
            "reasons": [
                "Community momentum extension detected price above EMA21 and SMA50.",
                f"RSI14 is {rsi14:.1f} with volume at {volume_ratio:.2f}x recent baseline.",
                "ATR-based stop and ladder targets were generated by the extension strategy.",
            ],
        }
    ]


class Extension:
    manifest = ExtensionManifest(
        id="community-momentum-pack",
        name="Community Momentum Pack",
        version="0.1.0",
        description="Example local extension that registers an executable momentum strategy, indicator metadata, and a UI surface.",
        capabilities=("strategy", "indicator", "ui_panel"),
        permissions=("read_market_data", "render_ui"),
        settings=(
            ExtensionSetting(
                key="enabled",
                label="Enabled",
                type="boolean",
                description="Enable this extension after restart.",
                default=False,
            ),
        ),
    )

    def register(self, context) -> None:
        context.register_strategy(
            StrategyDefinition(
                id="community-momentum-pullback",
                name="Community Momentum Pullback",
                description="Extension strategy that looks for persistent bullish trend pullbacks with participation.",
                setup_types=("community_momentum_pullback",),
                direction="long",
                source="extension",
                extension_id=self.manifest.id,
                candidate_factory=_community_momentum_candidates,
            )
        )
        context.register_indicator(
            IndicatorDefinition(
                id="community-volume-participation",
                name="Community Volume Participation",
                category="participation",
                description="Extension metadata for volume-ratio participation checks.",
                inputs=("volume",),
                outputs=("volume_ratio",),
                maturity="computed",
                source="extension",
                extension_id=self.manifest.id,
            )
        )
        context.register_surface(
            ExtensionSurfaceDefinition(
                id="community-momentum-dashboard-panel",
                name="Community Momentum Dashboard Panel",
                category="ui_panel",
                description="Example extension UI panel surface declaration for future dashboard rendering.",
                permissions=("render_ui",),
                maturity="planned",
                source="extension",
                extension_id=self.manifest.id,
            )
        )

    def health(self) -> dict[str, object]:
        return {"status": "ok", "loaded": True, "strategy": "community_momentum_pullback"}
